version: '3.8'

services:
  postgres:
    image: postgres:14.1
    restart: always
    container_name: postgres_course
    environment:
      POSTGRES_DB: ${DB_NAME:-course}
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres} 
    ports:
      - ${DB_PORT:-5432}:5432
    volumes:
      - ./docker/pgdata:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3.9.13-management
    container_name: rabbitmq_course
    hostname: rabbitmq
    ports:
      - ${RABBITMQ_PORT_1:-5672}:5672
      - ${RABBITMQ_PORT_2:-15672}:15672
    restart: always
    volumes:
      - ./docker/rabbitmqdata:/var/lib/rabbitmq