version: '3.8'

services:
  postgres:
    image: postgres:14.1
    restart: always
    container_name: postgres_course
    environment:
      POSTGRES_DB: ${DB_NAME:-course}
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres} 
    ports:
      - ${DB_PORT:-5432}:5432
    volumes:
      - ./docker/pgdata:/var/lib/postgresql/data
  redis:
    image: redis:6.2
    container_name: redis_course
    ports:
      - ${REDIS_PORT:-6379}:6379
    restart: always
    volumes:
      - ./docker/redisdata:/data